# https://taplo.tamasfe.dev/configuration/file.html
include = ["*.toml", "src/**/*.toml", "test/**/*.toml", "tool/**/*.toml"]

[formatting]
# https://taplo.tamasfe.dev/configuration/formatter-options.html
align_entries = false
align_comments = true
allowed_blank_lines = 2
array_auto_collapse = false
array_auto_expand = true
array_trailing_comma = true
column_width = 88
compact_arrays = true
compact_inline_tables = true
crlf = false
indent_string = "    "        # 4 spaces
indent_tables = true
reorder_keys = false
reorder_arrays = false
reorder_inline_tables = false
trailingNewline = true

[schema]
enabled = false
