# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

strict: true

site_name: NumType
site_description: Better typing stubs for NumPy
site_author: Joren Hammudoglu & NumPy Developers

site_url: https://numpy.github.io/numtype
repo_url: https://github.com/numpy/numtype
repo_name: numpy/numtype
edit_uri: blob/main/docs/

nav:
  - "User Guide": user_guide.md
  - "API Reference": reference.md
  - "Development": contributing.md

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/icon.svg

  features:
    - content.tabs.link
    - content.tooltips
    - navigation.path
    - navigation.indexes
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  font:
    text: Lato
    code: JetBrains Mono

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: fontawesome/solid/circle-half-stroke
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: pink
      toggle:
        icon: fontawesome/regular/moon
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: pink
      toggle:
        icon: fontawesome/regular/sun
        name: Switch to system preference

plugins:
  # https://github.com/mkdocstrings/autorefs
  - autorefs:
      resolve_closest: true

  # https://github.com/mondeja/mkdocs-include-markdown-plugin
  - include-markdown

  # https://github.com/byrnereese/mkdocs-minify-plugin
  - minify:
      minify_html: true

  # https://github.com/mkdocstrings/mkdocstrings
  # https://github.com/mkdocstrings/python
  - mkdocstrings:
      handlers:
        python:
          inventories:
            - url: https://docs.python.org/3/objects.inv
            - url: https://numpy.org/doc/stable/objects.inv
            - url: https://docs.scipy.org/doc/scipy/objects.inv
          options:
            docstring_section_style: list
            members_order: source
            show_root_heading: true
            show_source: false
            show_signature_annotations: true

  # https://squidfunk.github.io/mkdocs-material/plugins/search/
  - search

  # https://squidfunk.github.io/mkdocs-material/plugins/privacy/
  - privacy:
      enabled: !ENV [CI, false]

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      provider: github
      user: numpy
      repo: numtype

extra:
  analytics:
    provider: google
    property: G-JYJJ7JYLG1
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

extra_css:
  - style/theme.css

copyright: Copyright &copy; 2025 Joren Hammudoglu & NumPy Developers.
